#!/usr/bin/env python3
"""Self-documenting dashboard for the doc store.

Scans a store directory and (re)generates a one-row-per-library table: which tiers
exist (raw / INDEX / COMPACT / LOOKUP), page count, raw vs COMPACT token estimate,
the measured reduction %, and the COMPACT 'Indexed:' date. One generator, no GEN-block
framework — the drift gate is just `--check` (or CI running this then `git diff`).

Determinism note: every field is content-derived (token estimate, the `Indexed:` line
inside COMPACT.md) — never file mtimes — so regenerating on any machine/checkout yields
byte-identical output, which is what makes the `git diff --exit-code` drift gate work.

Usage:
  python -m scripts.store_index                       # live dashboard for your store
  python -m scripts.store_index --check               # exit 1 if the on-disk file is stale
  python -m scripts.store_index --store store/example --out store/INDEX.md [--check]
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.manifest import est_tokens, SKIP_FILES  # noqa: E402  (shared helpers)

DEFAULT_STORE = Path(os.environ.get("LLMDOCS_HOME") or (Path.home() / ".llmdocs")) / "docs"
_INDEXED_RE = re.compile(r"Indexed:\s*([0-9]{4}-[0-9]{2}-[0-9]{2})")


def _raw_pages(lib: Path) -> list[Path]:
    return [p for p in lib.rglob("*.md")
            if p.name not in SKIP_FILES and "_raw_html" not in p.parts]


def _indexed_date(compact: Path) -> str:
    if not compact.exists():
        return "—"
    m = _INDEXED_RE.search(compact.read_text(encoding="utf-8", errors="ignore"))
    return m.group(1) if m else "—"


def _lookup_libs(store: Path) -> set[str]:
    """Library names that have at least one line in the global LOOKUP.md."""
    lookup = store / "LOOKUP.md"
    if not lookup.exists():
        return set()
    libs = set()
    for line in lookup.read_text(encoding="utf-8", errors="ignore").splitlines():
        if "|" in line:
            libs.add(line.split("|", 1)[0].strip())
    return libs


def render(store: Path) -> str:
    if not store.is_dir():
        return f"# llmdocs — Store Dashboard\n\n_No store at `{store}`._\n"

    lookup_libs = _lookup_libs(store)
    rows, tot_pages, tot_raw, tot_compact = [], 0, 0, 0
    for lib in sorted(p for p in store.iterdir() if p.is_dir()):
        pages = _raw_pages(lib)
        raw_tok = sum(est_tokens(p.read_text(encoding="utf-8", errors="ignore")) for p in pages)
        compact = lib / "COMPACT.md"
        compact_tok = est_tokens(compact.read_text(encoding="utf-8", errors="ignore")) if compact.exists() else 0
        reduction = f"{(1 - compact_tok / raw_tok) * 100:.2f}%" if (compact_tok and raw_tok) else "—"
        tiers = "".join([
            "R" if pages else "·",
            "I" if (lib / "INDEX.md").exists() else "·",
            "C" if compact.exists() else "·",
            "L" if lib.name in lookup_libs else "·",
        ])
        rows.append((lib.name, tiers, len(pages), raw_tok, compact_tok, reduction,
                     _indexed_date(compact)))
        tot_pages += len(pages)
        tot_raw += raw_tok
        tot_compact += compact_tok

    lines = [
        "# llmdocs — Store Dashboard",
        "",
        "_Generated by `python -m scripts.store_index` — do not hand-edit._ Tiers: "
        "**R**aw · **I**NDEX · **C**OMPACT · **L**OOKUP. Tokens estimated at chars/4.",
        "",
        f"**{len(rows)} libraries · {tot_pages} pages · raw≈{tot_raw:,} tok · "
        f"COMPACT≈{tot_compact:,} tok**",
        "",
        "| Library | Tiers | Pages | Raw tok | COMPACT tok | Reduction | Indexed |",
        "|---------|:-----:|------:|--------:|------------:|----------:|:-------:|",
    ]
    for name, tiers, pages, raw_tok, compact_tok, reduction, indexed in rows:
        ctok = f"{compact_tok:,}" if compact_tok else "—"
        lines.append(f"| {name} | `{tiers}` | {pages} | {raw_tok:,} | {ctok} | {reduction} | {indexed} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="regenerate the store dashboard (store/INDEX.md)")
    ap.add_argument("--store", type=Path, default=DEFAULT_STORE, help="store docs dir to scan")
    ap.add_argument("--out", type=Path, default=None, help="output file (default: <store>/INDEX.md)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the on-disk file is stale")
    args = ap.parse_args()

    out = args.out or (args.store / "INDEX.md")
    content = render(args.store)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != content:
            print(f"STALE: {out} differs from regenerated dashboard. Run `python -m scripts.store_index`"
                  + (f" --store {args.store} --out {out}" if args.out else "") + ".", file=sys.stderr)
            return 1
        print(f"up to date: {out}")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
